version: '3.1'

services:
  db:
    container_name: db
    image: kapua/kapua-sql:${IMAGE_VERSION}
    ports:
      - "3306:3306"
    volumes:
      - "./h2-db:/var/opt/h2/data"
  es:
    container_name: es
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - cluster.name=kapua-datastore
      - discovery.type=single-node
      - transport.host=_site_
      - transport.ping_schedule=-1
      - transport.tcp.connect_timeout=30s
  events-broker:
    container_name: events-broker
    image: kapua/kapua-events-broker:${IMAGE_VERSION}
    ports:
      - "5672:5672"
  message-broker:
    image: kapua/kapua-broker-artemis:${IMAGE_VERSION}
    container_name: message-broker
    expose:
      - 1893
    ports:
      - "1883:1883"
      - "1893:1893"
      - "8883:8883"
      - "5682:5672"
      - "61616:61616"
    depends_on:
      - db
      - events-broker
    environment:
      - CRYPTO_SECRET_KEY
      - KAPUA_DISABLE_SSL=false
      - KAPUA_DISABLE_DATASTORE
      - KAPUA_CRT=$(cat /ssl/host.cert)
      - KAPUA_CA
      - KAPUA_KEY=$(cat /ssl/host.key)
      - KAPUA_KEY_PASSWORD=password
      - KAPUA_KEYSTORE
      - KAPUA_KEYSTORE_PASSWORD
      - LOGBACK_LOG_LEVEL
  service-authentication:
    image: kapua/kapua-service-authentication:${IMAGE_VERSION}
    container_name: service-auth
    ports:
      - 8100:8080
    depends_on:
      - db
      - events-broker
    environment:
      - LOGBACK_LOG_LEVEL
  consumer-telemetry:
    container_name: consumer-telemetry
    image: kapua/kapua-consumer-telemetry:${IMAGE_VERSION}
    ports:
      - "8090:8080"
    depends_on:
      - db
      - es
      - events-broker
      - message-broker
    environment:
      - BROKER_URL
      - CRYPTO_SECRET_KEY
      - LOGBACK_LOG_LEVEL
  consumer-lifecycle:
    container_name: consumer-lifecycle
    image: kapua/kapua-consumer-lifecycle:${IMAGE_VERSION}
    ports:
      - "8091:8080"
    depends_on:
      - db
      - events-broker
      - message-broker
    environment:
      - BROKER_URL
      - CRYPTO_SECRET_KEY
      - LOGBACK_LOG_LEVEL
  kapua-console:
    container_name: kapua-console
    image: kapua/kapua-console:${IMAGE_VERSION}
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - db
      - es
      - events-broker
      - message-broker
    environment:
      #- KEYSTORE_NAME=keystore-name
      - CRYPTO_SECRET_KEY
      - KAPUA_DISABLE_SSL=false
      - KAPUA_DISABLE_DATASTORE
      - KAPUA_CA
      - KAPUA_CRT=$(cat /ssl/host.cert)
      - KAPUA_KEY=$(cat /ssl/host.key)
      - KAPUA_KEY_PASSWORD=password
      - KAPUA_KEYSTORE=kapua-keystore
      - KAPUA_KEYSTORE_PASSWORD
      - LOGBACK_LOG_LEVEL
      - KAPUA_CONSOLE_URL
      - KAPUA_OPENID_JWT_ISSUER
      - KAPUA_OPENID_CLIENT_ID
      - KAPUA_OPENID_CLIENT_SECRET
      - KAPUA_OPENID_JWT_AUDIENCE
      - KAPUA_OPENID_AUTH_ENDPOINT
      - KAPUA_OPENID_TOKEN_ENDPOINT
      - KAPUA_OPENID_LOGOUT_ENDPOINT
      - KEYCLOAK_URL
      - KEYCLOAK_CLIENT_ID
      - KEYCLOAK_REALM
      - JETTY_BASE=/var/opt/jetty
    volumes:
      - "/Users/massimiliano.deluise/Desktop/tdl-salvatore/:/ssl"
  kapua-api:
    container_name: kapua-api
    image: kapua/kapua-api:${IMAGE_VERSION}
    ports:
      - "8081:8080"
      - "8444:8443"
    depends_on:
      - db
      - es
      - events-broker
      - message-broker
    environment:
      - API_CORS_ORIGINS_ALLOWED
      - CRYPTO_SECRET_KEY
      - KAPUA_DISABLE_SSL=false
      - KAPUA_DISABLE_DATASTORE
      - KAPUA_CA
      - KAPUA_CRT=$(cat /ssl/host.cert)
      - KAPUA_KEY=$(cat /ssl/host.key)
      - KAPUA_KEY_PASSWORD=password
      - LOGBACK_LOG_LEVEL
      - SWAGGER=${KAPUA_SWAGGER_ENABLE:-true}
  job-engine:
    container_name: job-engine
    image: kapua/kapua-job-engine:${IMAGE_VERSION}
    expose:
      - 8080
    depends_on:
      - db
      - events-broker
      - message-broker
    environment:
      - CRYPTO_SECRET_KEY
      - KAPUA_DISABLE_SSL=false
      - KAPUA_DISABLE_DATASTORE
      - KAPUA_CA
      - KAPUA_CRT=$(cat /ssl/host.cert)
      - KAPUA_KEY=$(cat /ssl/host.key)
      - KAPUA_KEY_PASSWORD=password
      - LOGBACK_LOG_LEVEL
